### PR TITLE
CMake added as build requirement

### PR DESCRIPTION
**Pull request by pgrohs**
I have added "cmake_installer/[>3.1]@conan/stable" to the build requirement of the recipe.

### CODE REVIEW

**Comment by uilianries** [comment]
Hi @pgrohs !

Why do you need this?

Usually we don't add cmake explicit because most of environments have cmake installed, including all Docker images used by us.

If you need to install cmake in your environment, I recommend you adding in your profile:

```
[build_requires]
*:cmake_installer/[>3.1]@conan/stable
```

**Comment by pgrohs** [comment]
Hi @uilianries,

thank you for your suggestion. Unfortunately, putting dependencies in profiles is not an option for us.  If my modifications are not convenient for others I will withdraw my PR.

**Comment by SSE4** [comment]
this should be harmless:
```
def build_requirements(self):
  if not tools.which("cmake"):
    self.build_requires("cmake_installer/[>3.1]@conan/stable")
```

**Comment by uilianries** [comment]
@SSE4 I agree

**Comment by SSE4** [comment]
outdated by https://github.com/bincrafters/conan-fmt/pull/20

**Comment by uilianries** [comment]
@pgrohs please, update your local copy, the new version should contain cmake_installer supported.

**Comment by pgrohs** [comment]
@uilianries Great! Thanks a lot.

**Pull request closed without merging**
